// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "ninjaImage":return img`
........................
........................
........................
........................
.........fffff..........
........fffffff.........
.....f.fffffffff........
......ffbfffffbf........
.....f.fd11b11df........
.......ff1fdf1ff........
........fffffff.........
.........fffff..........
........fffffff.........
.......fffffffff........
.......fffffffff........
......f.fffffff.f.......
......f.fffffff.f.......
.........fffff..........
.........ff.ff..........
........fff.fff.........
........................
........................
........................
........................
`;
            case "image2":
            case "starImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . f f . . . . . . . . . 
. . . . . . f f . . . . . . . . 
. . . . . . f b f . . . . . . . 
. . . . . . f c f . . . f . . . 
. . . . f f c a c f f f f . . . 
. . . f b c a 3 a c b f . . . . 
. . f f f f c a c f f . . . . . 
. . f . . . f c f . . . . . . . 
. . . . . . f b f . . . . . . . 
. . . . . . . f f . . . . . . . 
. . . . . . . . f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "ninjaImage0":return img`
........................
........................
........................
........................
.........fffff..........
........fffffff.........
.....f.fffffffff........
......ffbfffffbf........
.....f.fd11b11df........
.......ff1fdf1ff........
........fffffff.........
.........fffff..........
........fffffff.........
.......fffffffff........
.......fffffffff........
......f.fffffff.f.......
......f.fffffff.f.......
.........fffff..........
.........ff.ff..........
........fff.fff.........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
